# Generated by Django 5.2.7 on 2025-10-11 19:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('term_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)])),
                ('monthly_payment', models.DecimalField(decimal_places=2, help_text='EMI amount to be paid', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monthly_payments_made_on_time', models.PositiveIntegerField(default=0, help_text='Count of EMIs paid on time for credit score', validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_payment_due_date', models.PositiveIntegerField(help_text='Day of the month when payment is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('loan_approved', models.BooleanField(db_index=True, default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.customer')),
            ],
            options={
                'db_table': 'loans',
                'indexes': [models.Index(fields=['customer_id'], name='loans_custome_ebe58d_idx'), models.Index(fields=['is_active'], name='loans_is_acti_1a4c2d_idx'), models.Index(fields=['customer_id', 'loan_approved'], name='loans_custome_4f7f78_idx')],
            },
        ),
    ]
